#!/usr/bin/env python3
"""Añade ~43 ejercicios a las lecciones l07-l16 para llevarlas a ~50 ejercicios."""
import json, os, sys

BASE = os.path.join(os.path.dirname(__file__), '..', 'data', 'lessons')

EXERCISES = {

"l07-verbos-masu": [
  {"type":"exercise-mc","prompt":"¿Cómo se dice 'como' (I eat) en forma ます?","options":["たべます","たべます","たべます","たべます"],"answer":"たべます"},
  {"type":"exercise-mc","prompt":"¿Cómo se dice 'no bebo' en forma ます negativa?","options":["のみません","のみます","のみました","のみませんでした"],"answer":"のみません"},
  {"type":"exercise-mc","prompt":"¿Cómo se dice 'estudié' (pasado afirmativo)?","options":["べんきょうしました","べんきょうします","べんきょうしません","べんきょうしませんでした"],"answer":"べんきょうしました"},
  {"type":"exercise-mc","prompt":"¿Cómo se dice 'no fui' (pasado negativo)?","options":["いきませんでした","いきません","いきました","いきます"],"answer":"いきませんでした"},
  {"type":"exercise-mc","prompt":"La raíz ます de 書く (かく) es:","options":["書き","書く","書か","書け"],"answer":"書き"},
  {"type":"exercise-mc","prompt":"La raíz ます de 食べる (たべる) es:","options":["食べ","食べる","食ば","食び"],"answer":"食べ"},
  {"type":"exercise-mc","prompt":"La raíz ます de する (hacer) es:","options":["し","す","せ","さ"],"answer":"し"},
  {"type":"exercise-mc","prompt":"La raíz ます de 来る (くる) es:","options":["き","く","こ","か"],"answer":"き"},
  {"type":"exercise-mc","prompt":"¿Qué terminación indica propuesta ('vamos a…')?","options":["ましょう","ますか","ました","ません"],"answer":"ましょう"},
  {"type":"exercise-mc","prompt":"¿Qué terminación indica invitación ('¿vamos a…?')?","options":["ましょうか","ませんか","ましたか","ますか"],"answer":"ましょうか"},
  {"type":"exercise-mc","prompt":"¿Qué terminación indica invitación negativa ('¿por qué no…?')?","options":["ませんか","ましょうか","ませんでした","ません"],"answer":"ませんか"},
  {"type":"exercise-mc","prompt":"¿A qué grupo pertenece 帰る (かえる, volver)?","options":["Godan","Ichidan","Irregular","Ninguno"],"answer":"Godan"},
  {"type":"exercise-mc","prompt":"¿A qué grupo pertenece 起きる (おきる, levantarse)?","options":["Ichidan","Godan","Irregular","Ninguno"],"answer":"Ichidan"},
  {"type":"exercise-mc","prompt":"La forma ます presente de 聞く (きく, escuchar) es:","options":["聞きます","聞します","聞ます","聞えます"],"answer":"聞きます"},
  {"type":"exercise-mc","prompt":"La forma ます presente de 話す (はなす, hablar) es:","options":["話します","話きます","話ます","話めます"],"answer":"話します"},
  {"type":"exercise-mc","prompt":"La forma ます presente de 読む (よむ, leer) es:","options":["読みます","読きます","読ます","読えます"],"answer":"読みます"},
  {"type":"exercise-mc","prompt":"¿Cuál de estos verbos es irregular?","options":["する","書く","食べる","飲む"],"answer":"する"},
  {"type":"exercise-mc","prompt":"「毎朝ジョギングを___。」(Hago jogging cada mañana.)","options":["します","しません","しました","しましょう"],"answer":"します"},
  {"type":"exercise-mc","prompt":"「昨日は何も___。」(Ayer no comí nada.)","options":["たべませんでした","たべません","たべました","たべます"],"answer":"たべませんでした"},
  {"type":"exercise-mc","prompt":"「一緒に映画を___か。」(¿Vemos una película juntos?)","options":["みませんか","みません","みましょう","みます"],"answer":"みませんか"},
  {"type":"exercise-mc","prompt":"¿Cuántos verbos irregulares hay en japonés?","options":["2","3","5","10"],"answer":"2"},
  {"type":"exercise-mc","prompt":"¿Qué verbo significa 'venir' en japonés?","options":["来る（くる）","行く（いく）","帰る（かえる）","出る（でる）"],"answer":"来る（くる）"},
  {"type":"exercise-tf","statement":"「飲む」es un verbo ichidan.","answer":False},
  {"type":"exercise-tf","statement":"「見る」es un verbo ichidan.","answer":True},
  {"type":"exercise-tf","statement":"La forma ます negativa de します es しません.","answer":True},
  {"type":"exercise-tf","statement":"「します」y「する」son dos verbos diferentes.","answer":False},
  {"type":"exercise-tf","statement":"En japonés el verbo siempre va al final de la oración.","answer":True},
  {"type":"exercise-tf","statement":"ましょう expresa un hecho pasado.","answer":False},
  {"type":"exercise-tf","statement":"「来ます」es la forma ます de 来る.","answer":True},
  {"type":"exercise-tf","statement":"「ませんか」es más directo que「ましょうか」.","answer":False},
  {"type":"exercise-gap","prompt":"毎日日本語を___。(Estudio japonés todos los días.)","options":["べんきょうします","べんきょうしません","べんきょうしました","べんきょうしましょう"],"answer":"べんきょうします","hint":"presente afirmativo"},
  {"type":"exercise-gap","prompt":"明日は学校に___。(Mañana no voy a la escuela.)","options":["いきません","いきます","いきました","いきましょう"],"answer":"いきません","hint":"presente negativo"},
  {"type":"exercise-gap","prompt":"先週、本を三冊___。(La semana pasada leí tres libros.)","options":["よみました","よみます","よみません","よみましょう"],"answer":"よみました","hint":"pasado afirmativo"},
  {"type":"exercise-gap","prompt":"昨日はぜんぜんねません___。(Ayer no dormí nada.)","options":["でした","ました","ました","でした"],"answer":"でした","hint":"pasado negativo completo"},
  {"type":"exercise-gap","prompt":"一緒に昼ご飯を食べ___か。(¿Comemos juntos el almuerzo?)","options":["ましょう","ません","ます","ました"],"answer":"ましょう","hint":"propuesta"},
  {"type":"exercise-gap","prompt":"ピアノを___か。(¿Tocas el piano?)","options":["ひきます","ひきます","ひきます","ひきます"],"answer":"ひきます","hint":"presente afirmativo interrogativo"},
],

"l08-adjetivos": [
  {"type":"exercise-mc","prompt":"¿Cómo se dice 'no es caro' (adj-い negativo, informal)?","options":["たかくない","たかじゃない","たかいじゃない","たかくありません"],"answer":"たかくない"},
  {"type":"exercise-mc","prompt":"¿Cómo se dice 'era grande' (adj-い pasado)?","options":["おおきかった","おおきくた","おおきだった","おおきいた"],"answer":"おおきかった"},
  {"type":"exercise-mc","prompt":"¿Cómo se dice 'no era divertido' (adj-い pasado negativo)?","options":["たのしくなかった","たのしくなかった","たのしじゃなかった","たのしいじゃなかった"],"answer":"たのしくなかった"},
  {"type":"exercise-mc","prompt":"¿Cómo modifica 静か (しずか) a un sustantivo?","options":["しずかなまち","しずかまち","しずかいまち","しずかのまち"],"answer":"しずかなまち"},
  {"type":"exercise-mc","prompt":"¿Cómo se dice 'no es tranquilo/a' (adj-な negativo formal)?","options":["しずかではありません","しずかじゃあります","しずかくありません","しずかじゃない"],"answer":"しずかではありません"},
  {"type":"exercise-mc","prompt":"¿Cuál de estos es adjetivo な, aunque termine en い?","options":["きれい","たかい","おおきい","あつい"],"answer":"きれい"},
  {"type":"exercise-mc","prompt":"¿Cómo se forma el negativo informal de un adj-い?","options":["Quitar い y añadir くない","Quitar い y añadir じゃない","Añadir ではない al final","Añadir くありません"],"answer":"Quitar い y añadir くない"},
  {"type":"exercise-mc","prompt":"La forma pasada formal de たのしい es:","options":["たのしかったです","たのしくなりました","たのしいでした","たのしくでした"],"answer":"たのしかったです"},
  {"type":"exercise-mc","prompt":"¿Cuál es el negativo formal (polite) de adj-い 大きい?","options":["大きくありません","大きじゃありません","大きくないです","大きいではありません"],"answer":"大きくありません"},
  {"type":"exercise-mc","prompt":"「あのレストランは___です。」(Ese restaurante es famoso.)","options":["有名","有名な","有名い","有名く"],"answer":"有名"},
  {"type":"exercise-mc","prompt":"¿Cómo se dice 'una habitación tranquila' (modificador)?","options":["しずかなへや","しずかへや","しずかいへや","しずかくへや"],"answer":"しずかなへや"},
  {"type":"exercise-mc","prompt":"¿Cómo se dice 'una película interesante' (modificador)?","options":["おもしろいえいが","おもしろなえいが","おもしろくえいが","おもしろのえいが"],"answer":"おもしろいえいが"},
  {"type":"exercise-mc","prompt":"¿Cuántas clases principales de adjetivos hay en japonés?","options":["2","3","4","1"],"answer":"2"},
  {"type":"exercise-mc","prompt":"El adj-い 高い puede significar:","options":["caro y alto","solo caro","solo alto","solo difícil"],"answer":"caro y alto"},
  {"type":"exercise-mc","prompt":"La forma て del adj-い (para enlazar) se forma:","options":["Quitar い y añadir くて","Quitar い y añadir して","Añadir て directamente","Añadir にて"],"answer":"Quitar い y añadir くて"},
  {"type":"exercise-mc","prompt":"La forma て del adj-な (para enlazar) se forma:","options":["Añadir で","Añadir くて","Añadir にて","Añadir して"],"answer":"Añadir で"},
  {"type":"exercise-mc","prompt":"「この問題は___。」(Este problema es difícil.)","options":["むずかしいです","むずかしいなです","むずかしくです","むずかしなです"],"answer":"むずかしいです"},
  {"type":"exercise-mc","prompt":"¿Cuál de estas NO es adj-い?","options":["元気（げんき）","寒い（さむい）","新しい（あたらしい）","古い（ふるい）"],"answer":"元気（げんき）"},
  {"type":"exercise-tf","statement":"Los adjetivos い se conjugan directamente sin です en el pasado.","answer":True},
  {"type":"exercise-tf","statement":"きれい es un adjetivo い porque termina en い.","answer":False},
  {"type":"exercise-tf","statement":"Los adjetivos な usan な cuando modifican a un sustantivo.","answer":True},
  {"type":"exercise-tf","statement":"El pasado de おいしい (delicioso) es おいしかった.","answer":True},
  {"type":"exercise-tf","statement":"El negativo de adj-な 静か es 静かくない.","answer":False},
  {"type":"exercise-tf","statement":"大きい y 大きな tienen significados completamente distintos.","answer":False},
  {"type":"exercise-tf","statement":"「たのしくない」puede usarse sin です en lenguaje informal.","answer":True},
  {"type":"exercise-tf","statement":"Los adj-な pueden funcionar como sustantivos.","answer":True},
  {"type":"exercise-gap","prompt":"この料理は___です。(Esta comida es deliciosa.)","options":["おいしい","おいしな","おいしく","おいしの"],"answer":"おいしい","hint":"adj-い predicativo"},
  {"type":"exercise-gap","prompt":"あのひとは___ですね。(Esa persona es guapa, ¿verdad?)","options":["きれい","きれいい","きれいく","きれいな"],"answer":"きれい","hint":"adj-な predicativo sin な"},
  {"type":"exercise-gap","prompt":"___うみに行きたいです。(Quiero ir al mar bonito.)","options":["きれいな","きれい","きれいい","きれいく"],"answer":"きれいな","hint":"adj-な + sustantivo"},
  {"type":"exercise-gap","prompt":"きのうのテストは___。(El examen de ayer era difícil — informal past)","options":["むずかしかった","むずかしいだった","むずかしくだった","むずかしかった"],"answer":"むずかしかった","hint":"adj-い pasado informal"},
  {"type":"exercise-gap","prompt":"このへやは___じゃないです。(Esta habitación no es tranquila.)","options":["しずか","しずかな","しずかく","しずかい"],"answer":"しずか","hint":"adj-な negativo"},
  {"type":"exercise-gap","prompt":"たかくて、___レストランです。(Es un restaurante caro pero bueno.)","options":["いい","よく","よい","いいな"],"answer":"いい","hint":"いい = bueno"},
],

"l09-demostrativos": [
  {"type":"exercise-mc","prompt":"¿Qué serie (こ/そ/あ/ど) usa el hablante para algo cercano a él?","options":["こ-","そ-","あ-","ど-"],"answer":"こ-"},
  {"type":"exercise-mc","prompt":"¿Qué serie usa el oyente para algo cercano a él?","options":["そ-","こ-","あ-","ど-"],"answer":"そ-"},
  {"type":"exercise-mc","prompt":"¿Qué serie se usa para algo lejos de ambos?","options":["あ-","こ-","そ-","ど-"],"answer":"あ-"},
  {"type":"exercise-mc","prompt":"¿Qué serie se usa para preguntar?","options":["ど-","あ-","こ-","そ-"],"answer":"ど-"},
  {"type":"exercise-mc","prompt":"「___は何ですか？」(¿Qué es esto — cerca del hablante?)","options":["これ","それ","あれ","どれ"],"answer":"これ"},
  {"type":"exercise-mc","prompt":"「___はあなたのですか？」(¿Es eso tuyo — cerca del oyente?)","options":["それ","これ","あれ","どれ"],"answer":"それ"},
  {"type":"exercise-mc","prompt":"¿Cuál se usa para preguntar por un lugar?","options":["どこ","どれ","どの","どう"],"answer":"どこ"},
  {"type":"exercise-mc","prompt":"¿Cuál se usa como pronombre para preguntar '¿cuál?'?","options":["どれ","どの","どこ","どう"],"answer":"どれ"},
  {"type":"exercise-mc","prompt":"¿Cuál se usa como modificador para preguntar '¿qué…?'?","options":["どの","どれ","どこ","どう"],"answer":"どの"},
  {"type":"exercise-mc","prompt":"「___本を読んでいますか？」(¿Qué libro estás leyendo?)","options":["どの","どこ","どれ","どう"],"answer":"どの"},
  {"type":"exercise-mc","prompt":"「図書館は___ですか？」(¿Dónde está la biblioteca?)","options":["どこ","どれ","どの","どう"],"answer":"どこ"},
  {"type":"exercise-mc","prompt":"¿Cómo se dice 'esta persona' (cercana al hablante)?","options":["このひと","そのひと","あのひと","どのひと"],"answer":"このひと"},
  {"type":"exercise-mc","prompt":"¿Cómo se dice 'aquel edificio' (lejos de ambos)?","options":["あのビル","このビル","そのビル","どのビル"],"answer":"あのビル"},
  {"type":"exercise-mc","prompt":"¿Cómo se dice 'aquí' (lugar cercano al hablante)?","options":["ここ","そこ","あそこ","どこ"],"answer":"ここ"},
  {"type":"exercise-mc","prompt":"¿Cómo se dice 'allí / ahí' (lugar cercano al oyente)?","options":["そこ","ここ","あそこ","どこ"],"answer":"そこ"},
  {"type":"exercise-mc","prompt":"¿Cómo se dice 'allá' (lugar lejos de ambos)?","options":["あそこ","ここ","そこ","どこ"],"answer":"あそこ"},
  {"type":"exercise-mc","prompt":"¿Cómo se expresa 'de quién' o posesión en japonés?","options":["Sustantivo + の + sustantivo","Sustantivo + が + sustantivo","Sustantivo + は + sustantivo","Sustantivo + を + sustantivo"],"answer":"Sustantivo + の + sustantivo"},
  {"type":"exercise-mc","prompt":"「これは___のですか。」(¿De quién es esto?)","options":["だれ","なに","どこ","いつ"],"answer":"だれ"},
  {"type":"exercise-mc","prompt":"「わたしの___」significa:","options":["el/la mío/a","yo mismo","yo también","de mí"],"answer":"el/la mío/a"},
  {"type":"exercise-mc","prompt":"「___はやすいですか。」(¿Cuál es barato?) — pregunta por uno de una serie","options":["どれ","どこ","どの","どう"],"answer":"どれ"},
  {"type":"exercise-mc","prompt":"「この___は日本語で何ですか。」(¿Cómo se dice esto en japonés?)","options":["もの / これ","どこ","どれ","それ"],"answer":"もの / これ"},
  {"type":"exercise-mc","prompt":"¿Cuándo usas あの vs. その?","options":["あの: lejos de ambos; その: cerca del oyente","あの: cerca del oyente; その: lejos de ambos","Son intercambiables","あの siempre es demostrativo de lugar"],"answer":"あの: lejos de ambos; その: cerca del oyente"},
  {"type":"exercise-tf","statement":"この、その、あの siempre preceden directamente a un sustantivo.","answer":True},
  {"type":"exercise-tf","statement":"これ、それ、あれ son modificadores que van antes de un sustantivo.","answer":False},
  {"type":"exercise-tf","statement":"どこ pregunta por un lugar.","answer":True},
  {"type":"exercise-tf","statement":"どの puede usarse solo sin sustantivo.","answer":False},
  {"type":"exercise-tf","statement":"「あそこ」se refiere a un lugar lejano a todos los interlocutores.","answer":True},
  {"type":"exercise-tf","statement":"「そこ」y「あそこ」son intercambiables cuando el lugar está lejos del hablante.","answer":False},
  {"type":"exercise-tf","statement":"の marca posesión entre dos sustantivos.","answer":True},
  {"type":"exercise-tf","statement":"「どれ」puede referirse a uno de dos o más opciones.","answer":True},
  {"type":"exercise-gap","prompt":"___は私のかばんです。(Este es mi bolso — cerca del hablante.)","options":["これ","それ","あれ","どれ"],"answer":"これ","hint":"cerca del hablante"},
  {"type":"exercise-gap","prompt":"___の電話番号を教えてください。(Dime tu número de teléfono.)","options":["あなた","これ","それ","どこ"],"answer":"あなた","hint":"posesivo con の"},
  {"type":"exercise-gap","prompt":"駅は___ですか。(¿Dónde está la estación?)","options":["どこ","どれ","どの","そこ"],"answer":"どこ","hint":"pregunta de lugar"},
  {"type":"exercise-gap","prompt":"___本は面白いですか。(¿Es interesante ese libro — cerca del oyente?)","options":["その","この","あの","どの"],"answer":"その","hint":"serie そ- = cerca del oyente"},
  {"type":"exercise-gap","prompt":"___に日本語の学校がありますか。(¿Hay una escuela de japonés allá?)","options":["あそこ","ここ","そこ","どこ"],"answer":"あそこ","hint":"lejos de ambos"},
  {"type":"exercise-gap","prompt":"これはだれ___ですか。(¿De quién es esto?)","options":["の","は","が","を"],"answer":"の","hint":"partícula posesiva"},
],

"l10-existencia": [
  {"type":"exercise-mc","prompt":"¿Cuál usas para decir que hay una silla (objeto)?","options":["あります","います","です","する"],"answer":"あります"},
  {"type":"exercise-mc","prompt":"¿Cuál usas para decir que hay un perro?","options":["います","あります","です","ある"],"answer":"います"},
  {"type":"exercise-mc","prompt":"¿Cuál usas para decir que hay un robot?","options":["あります","います","です","ある"],"answer":"あります"},
  {"type":"exercise-mc","prompt":"¿Qué significa うえ?","options":["arriba / encima","abajo / debajo","delante","detrás"],"answer":"arriba / encima"},
  {"type":"exercise-mc","prompt":"¿Qué significa した?","options":["abajo / debajo","arriba / encima","dentro","al lado"],"answer":"abajo / debajo"},
  {"type":"exercise-mc","prompt":"¿Qué significa まえ?","options":["delante","detrás","dentro","fuera"],"answer":"delante"},
  {"type":"exercise-mc","prompt":"¿Qué significa うしろ?","options":["detrás","delante","arriba","abajo"],"answer":"detrás"},
  {"type":"exercise-mc","prompt":"¿Qué significa となり?","options":["al lado","dentro","fuera","entre"],"answer":"al lado"},
  {"type":"exercise-mc","prompt":"¿Qué significa なか?","options":["dentro / en el interior","fuera","al lado","sobre"],"answer":"dentro / en el interior"},
  {"type":"exercise-mc","prompt":"「机の___に本があります。」(Hay un libro SOBRE la mesa.)","options":["うえ","した","まえ","なか"],"answer":"うえ"},
  {"type":"exercise-mc","prompt":"「いすの___に猫がいます。」(Hay un gato DEBAJO de la silla.)","options":["した","うえ","となり","まえ"],"answer":"した"},
  {"type":"exercise-mc","prompt":"「冷蔵庫の___に牛乳があります。」(Hay leche DENTRO de la nevera.)","options":["なか","うえ","まえ","そと"],"answer":"なか"},
  {"type":"exercise-mc","prompt":"「本屋の___にコンビニがあります。」(Hay un conbini AL LADO de la librería.)","options":["となり","うしろ","まえ","した"],"answer":"となり"},
  {"type":"exercise-mc","prompt":"¿Qué partícula marca el sujeto de existencia?","options":["が","は","を","に"],"answer":"が"},
  {"type":"exercise-mc","prompt":"¿Qué partícula marca el lugar con あります/います?","options":["に","で","は","が"],"answer":"に"},
  {"type":"exercise-mc","prompt":"「どこに___がありますか。」(¿Dónde hay un banco?)","options":["銀行","本","学校","電車"],"answer":"銀行"},
  {"type":"exercise-mc","prompt":"¿Qué verbo de existencia usarías para un insecto?","options":["います","あります","ある","する"],"answer":"います"},
  {"type":"exercise-mc","prompt":"¿Qué verbo de existencia usarías para un árbol?","options":["あります","います","いる","する"],"answer":"あります"},
  {"type":"exercise-mc","prompt":"「トイレはどこに___か。」(¿Dónde está el baño?)","options":["ありますか","いますか","ですか","しますか"],"answer":"ありますか"},
  {"type":"exercise-mc","prompt":"¿Cuál es la forma negativa de あります?","options":["ありません","いません","ないです","あります"],"answer":"ありません"},
  {"type":"exercise-mc","prompt":"¿Cuál es la forma negativa de います?","options":["いません","ありません","いないです","います"],"answer":"いません"},
  {"type":"exercise-mc","prompt":"「駅の___に病院があります。」(Hay un hospital DETRÁS de la estación.)","options":["うしろ","まえ","となり","うえ"],"answer":"うしろ"},
  {"type":"exercise-tf","statement":"あります se usa tanto para objetos inanimados como para animales.","answer":False},
  {"type":"exercise-tf","statement":"います se usa para personas y animales.","answer":True},
  {"type":"exercise-tf","statement":"「机の下に本があります。」significa 'Hay un libro debajo de la mesa'.","answer":True},
  {"type":"exercise-tf","statement":"La partícula に marca el lugar de existencia con あります/います.","answer":True},
  {"type":"exercise-tf","statement":"「となり」significa exactamente lo mismo que「そば」(cerca de).","answer":False},
  {"type":"exercise-tf","statement":"Un robot (ロボット) usaría います porque puede moverse.","answer":False},
  {"type":"exercise-tf","statement":"「ここに」significa 'aquí (localización)'.","answer":True},
  {"type":"exercise-tf","statement":"「そこ」se puede usar con la partícula に para indicar lugar.","answer":True},
  {"type":"exercise-gap","prompt":"つくえの___に猫がいます。(Hay un gato encima de la mesa.)","options":["うえ","した","なか","まえ"],"answer":"うえ","hint":"encima"},
  {"type":"exercise-gap","prompt":"部屋の___にテレビがあります。(Hay una televisión dentro de la habitación.)","options":["なか","うえ","そと","うしろ"],"answer":"なか","hint":"dentro"},
  {"type":"exercise-gap","prompt":"学校の___に公園があります。(Hay un parque delante de la escuela.)","options":["まえ","うしろ","となり","した"],"answer":"まえ","hint":"delante"},
  {"type":"exercise-gap","prompt":"冷蔵庫の___に卵があります。(Hay huevos dentro de la nevera.)","options":["なか","うえ","まえ","うしろ"],"answer":"なか","hint":"dentro"},
  {"type":"exercise-gap","prompt":"猫は___にいます。(El gato está debajo.) ¿Debajo de qué? つくえの___。","options":["した","うえ","まえ","なか"],"answer":"した","hint":"debajo"},
  {"type":"exercise-gap","prompt":"本屋の___に花屋があります。(Hay una floristería al lado de la librería.)","options":["となり","うしろ","うえ","なか"],"answer":"となり","hint":"al lado"},
],

"l11-forma-te": [
  {"type":"exercise-mc","prompt":"La forma て de 食べる (たべる, comer) es:","options":["食べて","食べって","食べた","食べで"],"answer":"食べて"},
  {"type":"exercise-mc","prompt":"La forma て de 飲む (のむ, beber) es:","options":["飲んで","飲みて","飲んて","飲んだ"],"answer":"飲んで"},
  {"type":"exercise-mc","prompt":"La forma て de 書く (かく, escribir) es:","options":["書いて","書きて","書って","書くて"],"answer":"書いて"},
  {"type":"exercise-mc","prompt":"La forma て de 話す (はなす, hablar) es:","options":["話して","話せて","話さて","話いて"],"answer":"話して"},
  {"type":"exercise-mc","prompt":"La forma て de 来る (くる, venir) es:","options":["来て（きて）","来って","くて","こて"],"answer":"来て（きて）"},
  {"type":"exercise-mc","prompt":"La forma て de する (hacer) es:","options":["して","すて","せて","さて"],"answer":"して"},
  {"type":"exercise-mc","prompt":"La forma て de 買う (かう, comprar) es:","options":["買って","買いて","買うて","買えて"],"answer":"買って"},
  {"type":"exercise-mc","prompt":"La forma て de 待つ (まつ, esperar) es:","options":["待って","待ちて","待いて","待つて"],"answer":"待って"},
  {"type":"exercise-mc","prompt":"La forma て de 読む (よむ, leer) es:","options":["読んで","読みて","読いて","読んて"],"answer":"読んで"},
  {"type":"exercise-mc","prompt":"La forma て de 聞く (きく, escuchar) es:","options":["聞いて","聞きて","聞って","聞くて"],"answer":"聞いて"},
  {"type":"exercise-mc","prompt":"「まどを___ください。」(Por favor, abre la ventana.)","options":["あけて","あけます","あけました","あけましょう"],"answer":"あけて"},
  {"type":"exercise-mc","prompt":"「今、何をして___ますか？」(¿Qué estás haciendo ahora?)","options":["い","あり","あ","え"],"answer":"い"},
  {"type":"exercise-mc","prompt":"「テレビを見___います。」(Estoy viendo la tele.)","options":["て","で","を","に"],"answer":"て"},
  {"type":"exercise-mc","prompt":"~ている puede indicar:","options":["Acción en progreso O estado resultante","Solo acción en progreso","Solo estado resultante","Acción pasada"],"answer":"Acción en progreso O estado resultante"},
  {"type":"exercise-mc","prompt":"「結婚しています」significa:","options":["Está casado/a (estado)","Se está casando ahora","Se casó ayer","No está casado/a"],"answer":"Está casado/a (estado)"},
  {"type":"exercise-mc","prompt":"¿Qué indica ~てください?","options":["Petición educada","Propuesta conjunta","Negación","Pasado"],"answer":"Petición educada"},
  {"type":"exercise-mc","prompt":"「ゆっくり___ください。」(Por favor, habla despacio.)","options":["はなして","はなします","はなした","はなしましょう"],"answer":"はなして"},
  {"type":"exercise-mc","prompt":"La forma て de 帰る (かえる, volver) es:","options":["帰って","帰りて","帰いて","帰て"],"answer":"帰って"},
  {"type":"exercise-mc","prompt":"「ごはんを食べて、テレビを見ます。」¿Qué indica て aquí?","options":["Secuencia de acciones","Petición","Estado actual","Negación"],"answer":"Secuencia de acciones"},
  {"type":"exercise-mc","prompt":"La forma て de 行く (いく, ir) es irregular: es:","options":["行って","行きて","行いて","行くて"],"answer":"行って"},
  {"type":"exercise-mc","prompt":"La forma て de 死ぬ (しぬ, morir) es:","options":["死んで","死にて","死って","死ぬて"],"answer":"死んで"},
  {"type":"exercise-mc","prompt":"La forma て de 急ぐ (いそぐ, apresurarse) es:","options":["急いで","急ぎて","急って","急ぐて"],"answer":"急いで"},
  {"type":"exercise-tf","statement":"La forma て de する es して.","answer":True},
  {"type":"exercise-tf","statement":"La forma て de 行く es 行きて.","answer":False},
  {"type":"exercise-tf","statement":"~ている siempre indica una acción en progreso en este momento.","answer":False},
  {"type":"exercise-tf","statement":"~てください es una petición educada.","answer":True},
  {"type":"exercise-tf","statement":"La forma て enlaza acciones en secuencia.","answer":True},
  {"type":"exercise-tf","statement":"Los verbos godan que terminan en む forman て con んで.","answer":True},
  {"type":"exercise-tf","statement":"La forma て de 食べる es 食べって.","answer":False},
  {"type":"exercise-tf","statement":"「日本語を勉強しています。」puede significar 'Estoy estudiando japonés (ahora)'.","answer":True},
  {"type":"exercise-gap","prompt":"てを___ください。(Por favor, lávate las manos.)","options":["あらって","あらいます","あらいました","あらいましょう"],"answer":"あらって","hint":"forma て + ください"},
  {"type":"exercise-gap","prompt":"音楽を聞き___、勉強します。(Escucho música y estudio.)","options":["ながら","ています","て","てください"],"answer":"ながら","hint":"dos acciones simultáneas: ~ながら"},
  {"type":"exercise-gap","prompt":"今、本を___います。(Ahora estoy leyendo un libro.)","options":["よんで","よみて","よんで","よんでい"],"answer":"よんで","hint":"forma て de 読む"},
  {"type":"exercise-gap","prompt":"「すみません、もう一度___ください。」(Por favor, dígalo otra vez.)","options":["いって","いいます","いきます","いきましょう"],"answer":"いって","hint":"forma て de 言う"},
  {"type":"exercise-gap","prompt":"友達に電話を___、話しました。(Llamé a mi amigo y hablé.)","options":["かけて","かけます","かけました","かけて"],"answer":"かけて","hint":"secuencia con て"},
  {"type":"exercise-gap","prompt":"彼女は今、料理を___います。(Ella está cocinando ahora.)","options":["して","します","した","しましょう"],"answer":"して","hint":"~ている continuo"},
],

"l12-deseos-negacion": [
  {"type":"exercise-mc","prompt":"¿Cómo se forma ~たい (querer hacer)?","options":["Raíz ます + たい","Diccionario + たい","Forma て + たい","Forma た + い"],"answer":"Raíz ます + たい"},
  {"type":"exercise-mc","prompt":"「日本に行きたいです。」significa:","options":["Quiero ir a Japón","Fui a Japón","Iré a Japón","No quiero ir a Japón"],"answer":"Quiero ir a Japón"},
  {"type":"exercise-mc","prompt":"¿Cómo se forma el negativo plain de un verbo godan?","options":["Cambiar última vocal a あ + ない","Añadir ない al diccionario","Añadir くない al diccionario","Cambiar ます por ない"],"answer":"Cambiar última vocal a あ + ない"},
  {"type":"exercise-mc","prompt":"La forma ない de 飲む (のむ) es:","options":["飲まない","飲みない","飲んない","飲むない"],"answer":"飲まない"},
  {"type":"exercise-mc","prompt":"La forma ない de 食べる (たべる) es:","options":["食べない","食べまない","食べあない","食べくない"],"answer":"食べない"},
  {"type":"exercise-mc","prompt":"La forma ない de する es:","options":["しない","すない","せない","さない"],"answer":"しない"},
  {"type":"exercise-mc","prompt":"La forma ない de 来る (くる) es:","options":["こない","きない","くない","かない"],"answer":"こない"},
  {"type":"exercise-mc","prompt":"¿Qué indica ~ましょう?","options":["Propuesta ('vamos a…')","Deseo personal","Negación plain","Orden directa"],"answer":"Propuesta ('vamos a…')"},
  {"type":"exercise-mc","prompt":"¿Qué indica ~ましょうか?","options":["Oferta o sugerencia ('¿hacemos…?')","Propuesta directa","Deseo personal","Negación"],"answer":"Oferta o sugerencia ('¿hacemos…?')"},
  {"type":"exercise-mc","prompt":"「手伝いましょうか。」significa:","options":["¿Te ayudo?","¡Ayudemos!","No te ayudaré","Quiero ayudar"],"answer":"¿Te ayudo?"},
  {"type":"exercise-mc","prompt":"「一緒に食べましょう。」significa:","options":["¡Comamos juntos!","¿Comemos juntos?","Quiero comer","No como"],"answer":"¡Comamos juntos!"},
  {"type":"exercise-mc","prompt":"~たい solo se puede usar para hablar de:","options":["Los deseos del propio hablante","Los deseos de cualquier persona","Acciones pasadas","Acciones futuras obligatorias"],"answer":"Los deseos del propio hablante"},
  {"type":"exercise-mc","prompt":"¿Cómo se dice 'quiero beber agua'?","options":["水を飲みたいです","水が飲みたいです","水に飲みたいです","水で飲みたいです"],"answer":"水を飲みたいです"},
  {"type":"exercise-mc","prompt":"El negativo de ~たい es:","options":["~たくない","~たくありません (formal)","Ambas son correctas","~ないたい"],"answer":"Ambas son correctas"},
  {"type":"exercise-mc","prompt":"La forma ない de 書く (かく) es:","options":["書かない","書きない","書くない","書いない"],"answer":"書かない"},
  {"type":"exercise-mc","prompt":"La forma ない de 行く (いく) es:","options":["行かない","行きない","行くない","行いない"],"answer":"行かない"},
  {"type":"exercise-mc","prompt":"La forma ない de 話す (はなす) es:","options":["話さない","話しない","話すない","話せない"],"answer":"話さない"},
  {"type":"exercise-mc","prompt":"La forma ない de 帰る (かえる, godan) es:","options":["帰らない","帰りない","帰るない","帰れない"],"answer":"帰らない"},
  {"type":"exercise-mc","prompt":"La forma ない de 買う (かう) es:","options":["買わない","買いない","買うない","買えない"],"answer":"買わない"},
  {"type":"exercise-mc","prompt":"¿Cómo se expresa 'no quiero comer sushi'?","options":["すしを食べたくないです","すしを食べないたいです","すしを食べたいないです","すしが食べたくないです"],"answer":"すしを食べたくないです"},
  {"type":"exercise-mc","prompt":"「もう少し___ましょうか。」(¿Esperamos un poco más?)","options":["まち","まつ","まて","まき"],"answer":"まち"},
  {"type":"exercise-tf","statement":"~たい se forma añadiéndolo a la forma diccionario del verbo.","answer":False},
  {"type":"exercise-tf","statement":"La forma ない de する es しない.","answer":True},
  {"type":"exercise-tf","statement":"~ましょうか es una forma de ofrecer ayuda.","answer":True},
  {"type":"exercise-tf","statement":"「行かない」es el negativo plain de 行きます.","answer":True},
  {"type":"exercise-tf","statement":"~たい puede usarse para expresar deseos de otra persona en japonés estándar.","answer":False},
  {"type":"exercise-tf","statement":"El negativo de ~たい es ~たくない.","answer":True},
  {"type":"exercise-tf","statement":"「食べましょう」y「食べませんか」tienen el mismo significado exacto.","answer":False},
  {"type":"exercise-tf","statement":"La forma ない de un verbo ichidan se forma quitando る y añadiendo ない.","answer":True},
  {"type":"exercise-gap","prompt":"今日は出かけ___。(Hoy no salgo — plain negativo)","options":["ない","ません","なかった","ないです"],"answer":"ない","hint":"negativo plain"},
  {"type":"exercise-gap","prompt":"日本語が上手に___たいです。(Quiero hablar bien el japonés.)","options":["なり","なる","なって","なら"],"answer":"なり","hint":"raíz ます de なる"},
  {"type":"exercise-gap","prompt":"バッグを持ち___か。(¿Llevo yo el bolso? — oferta)","options":["ましょう","ませんか","たいです","ません"],"answer":"ましょう","hint":"oferta con ましょうか"},
  {"type":"exercise-gap","prompt":"すしを食べ___です。(Quiero comer sushi.)","options":["たい","ない","ます","ました"],"answer":"たい","hint":"deseo: raíz ます + たい"},
  {"type":"exercise-gap","prompt":"今日は何も食べ___。(Hoy no como nada — plain negativo)","options":["ない","ません","なかった","ないです"],"answer":"ない","hint":"plain negativo"},
  {"type":"exercise-gap","prompt":"一緒に公園を散歩し___。(Paseemos juntos por el parque.)","options":["ましょう","ましょうか","ませんか","ません"],"answer":"ましょう","hint":"propuesta ましょう"},
],

"l13-particulas-extra": [
  {"type":"exercise-mc","prompt":"「私___行きます。」(Yo también voy.) ¿Qué partícula?","options":["も","と","から","まで"],"answer":"も"},
  {"type":"exercise-mc","prompt":"「私は行きません。彼女___。」(Yo no voy. Ella tampoco.) ¿Qué partícula?","options":["も","と","から","まで"],"answer":"も"},
  {"type":"exercise-mc","prompt":"「田中さん___山田さんが来ます。」(Tanaka y Yamada vienen.) ¿Qué partícula?","options":["と","も","から","へ"],"answer":"と"},
  {"type":"exercise-mc","prompt":"「友達___映画を見ました。」(Vi una película CON mi amigo.) ¿Qué partícula?","options":["と","も","を","に"],"answer":"と"},
  {"type":"exercise-mc","prompt":"「東京___大阪まで行きました。」(Fui desde Tokio hasta Osaka.) ¿Qué partícula?","options":["から","まで","へ","に"],"answer":"から"},
  {"type":"exercise-mc","prompt":"「九時___五時まで働きます。」(Trabajo de 9 a 5.) ¿Qué partícula va en el primer hueco?","options":["から","まで","へ","に"],"answer":"から"},
  {"type":"exercise-mc","prompt":"「学校___家まで歩きます。」(Voy andando desde la escuela hasta casa.) ¿Qué partícula?","options":["から","まで","へ","と"],"answer":"から"},
  {"type":"exercise-mc","prompt":"「ここ___出口まで何分ですか。」(¿Cuántos minutos de aquí a la salida?) ¿Primera partícula?","options":["から","まで","へ","に"],"answer":"から"},
  {"type":"exercise-mc","prompt":"「日本___行きたいです。」(Quiero ir a Japón.) ¿Qué partícula?","options":["へ","に","で","を"],"answer":"へ"},
  {"type":"exercise-mc","prompt":"¿Cuál es la diferencia principal entre へ y に para destino?","options":["へ enfatiza dirección; に enfatiza destino/punto de llegada","Son idénticas","へ solo con personas; に solo con lugares","へ es informal; に es formal"],"answer":"へ enfatiza dirección; に enfatiza destino/punto de llegada"},
  {"type":"exercise-mc","prompt":"「電車___来ました。」(Vine en tren.) ¿Qué partícula?","options":["で","に","を","から"],"answer":"で"},
  {"type":"exercise-mc","prompt":"「日本語___話しましょう。」(Hablemos en japonés.) ¿Qué partícula?","options":["で","に","を","へ"],"answer":"で"},
  {"type":"exercise-mc","prompt":"「病気___学校を休みました。」(Falté a la escuela por enfermedad.) ¿Qué partícula?","options":["で","に","を","から"],"answer":"で"},
  {"type":"exercise-mc","prompt":"「もう一杯___？」(¿Una copa más también?) ¿Qué partícula?","options":["も","と","から","まで"],"answer":"も"},
  {"type":"exercise-mc","prompt":"「東京___大阪___何時間かかりますか。」(¿Cuántas horas de Tokio a Osaka?)","options":["から / まで","まで / から","に / へ","へ / に"],"answer":"から / まで"},
  {"type":"exercise-mc","prompt":"「来週___テストがあります。」(Hay un examen desde la semana que viene.) ¿Qué partícula?","options":["から","まで","に","で"],"answer":"から"},
  {"type":"exercise-mc","prompt":"「図書館は六時___閉まります。」(La biblioteca cierra A las seis.) ¿Qué partícula?","options":["まで","から","に","で"],"answer":"まで"},
  {"type":"exercise-mc","prompt":"「バス___自転車___来ました。」(Vine en autobús o en bici — listado) ¿Qué partícula entre opciones de transporte?","options":["か","と","も","で"],"answer":"か"},
  {"type":"exercise-mc","prompt":"「母___父___家にいます。」(Mi madre y mi padre están en casa.)","options":["と","も","から","まで"],"answer":"と"},
  {"type":"exercise-mc","prompt":"¿Qué partícula indica punto de inicio temporal?","options":["から","まで","に","で"],"answer":"から"},
  {"type":"exercise-mc","prompt":"¿Qué partícula indica punto límite o fin?","options":["まで","から","に","へ"],"answer":"まで"},
  {"type":"exercise-mc","prompt":"「毎日６時間___勉強します。」(Estudio hasta 6 horas todos los días.) ¿Qué partícula?","options":["まで","から","に","で"],"answer":"まで"},
  {"type":"exercise-tf","statement":"も puede significar 'también' y 'tampoco'.","answer":True},
  {"type":"exercise-tf","statement":"と siempre significa 'y'. No puede significar 'con'.","answer":False},
  {"type":"exercise-tf","statement":"から indica punto de inicio (lugar o tiempo).","answer":True},
  {"type":"exercise-tf","statement":"まで indica punto final o límite.","answer":True},
  {"type":"exercise-tf","statement":"へ y に son completamente intercambiables en todos los contextos.","answer":False},
  {"type":"exercise-tf","statement":"で puede indicar el medio de transporte.","answer":True},
  {"type":"exercise-tf","statement":"「私もです。」significa 'Yo también'.","answer":True},
  {"type":"exercise-tf","statement":"から puede indicar causa o razón.","answer":True},
  {"type":"exercise-gap","prompt":"毎朝七時___起きます。(Me levanto A las 7 cada mañana.)","options":["から","まで","に","で"],"answer":"から","hint":"punto de inicio = から"},
  {"type":"exercise-gap","prompt":"東京___大阪まで新幹線で行きます。(Voy en shinkansen de Tokio a Osaka.)","options":["から","まで","へ","に"],"answer":"から","hint":"punto de inicio"},
  {"type":"exercise-gap","prompt":"駅___ここまで歩いて十分です。(Son 10 minutos andando desde la estación.)","options":["から","まで","に","で"],"answer":"から","hint":"desde = から"},
  {"type":"exercise-gap","prompt":"私___行きます。(Yo también voy.)","options":["も","と","から","まで"],"answer":"も","hint":"también = も"},
  {"type":"exercise-gap","prompt":"友達___勉強しました。(Estudié CON mi amigo.)","options":["と","も","に","で"],"answer":"と","hint":"con (persona) = と"},
  {"type":"exercise-gap","prompt":"日本___来ました。(Vine a Japón — énfasis en dirección.)","options":["へ","に","から","まで"],"answer":"へ","hint":"dirección = へ"},
],

"l14-interrogativos": [
  {"type":"exercise-mc","prompt":"¿Qué interrogativo pregunta por cosas u objetos?","options":["なに / なん","だれ","どこ","いつ"],"answer":"なに / なん"},
  {"type":"exercise-mc","prompt":"¿Qué interrogativo pregunta por personas?","options":["だれ","なに","どこ","いつ"],"answer":"だれ"},
  {"type":"exercise-mc","prompt":"¿Qué interrogativo pregunta por lugares?","options":["どこ","いつ","だれ","なに"],"answer":"どこ"},
  {"type":"exercise-mc","prompt":"¿Qué interrogativo pregunta por el tiempo?","options":["いつ","どこ","だれ","なに"],"answer":"いつ"},
  {"type":"exercise-mc","prompt":"¿Qué interrogativo pregunta por el precio?","options":["いくら","いくつ","なに","どう"],"answer":"いくら"},
  {"type":"exercise-mc","prompt":"¿Qué interrogativo pregunta por la cantidad (cosas)?","options":["いくつ","いくら","なに","どう"],"answer":"いくつ"},
  {"type":"exercise-mc","prompt":"¿Qué interrogativo pregunta por el modo o estado ('¿cómo?')?","options":["どう","どこ","だれ","いつ"],"answer":"どう"},
  {"type":"exercise-mc","prompt":"¿Qué interrogativo pregunta por la razón ('¿por qué?')?","options":["どうして / なぜ","どう","いつ","なに"],"answer":"どうして / なぜ"},
  {"type":"exercise-mc","prompt":"¿Cuándo se usa なん en vez de なに?","options":["Antes de contador o cuando sigue una consonante","Siempre","Nunca","Solo en preguntas formales"],"answer":"Antes de contador o cuando sigue una consonante"},
  {"type":"exercise-mc","prompt":"「___時に来ますか。」(¿A qué hora vienes?) ¿Qué interrogativo?","options":["なん","いつ","どこ","だれ"],"answer":"なん"},
  {"type":"exercise-mc","prompt":"「これは___ですか。」(¿Qué es esto?)","options":["なに","だれ","どこ","いつ"],"answer":"なに"},
  {"type":"exercise-mc","prompt":"「あの人は___ですか。」(¿Quién es esa persona?)","options":["だれ","なに","どこ","いつ"],"answer":"だれ"},
  {"type":"exercise-mc","prompt":"「誕生日は___ですか。」(¿Cuándo es tu cumpleaños?)","options":["いつ","どこ","だれ","なに"],"answer":"いつ"},
  {"type":"exercise-mc","prompt":"「このかばんは___ですか。」(¿Cuánto cuesta este bolso?)","options":["いくら","いくつ","なに","どう"],"answer":"いくら"},
  {"type":"exercise-mc","prompt":"「りんごを___買いますか。」(¿Cuántas manzanas compras?)","options":["いくつ","いくら","なに","どこ"],"answer":"いくつ"},
  {"type":"exercise-mc","prompt":"「日本語は___ですか。」(¿Cómo es el japonés — tu opinión?)","options":["どう","どこ","なに","だれ"],"answer":"どう"},
  {"type":"exercise-mc","prompt":"「___行きたいですか。」(¿A dónde quieres ir?)","options":["どこに","なにに","だれに","いつに"],"answer":"どこに"},
  {"type":"exercise-mc","prompt":"「___から来ましたか。」(¿De dónde viniste?)","options":["どこ","いつ","だれ","なに"],"answer":"どこ"},
  {"type":"exercise-mc","prompt":"「お名前は___ですか。」(¿Cómo se llama usted?)","options":["なん","なに","だれ","どう"],"answer":"なん"},
  {"type":"exercise-mc","prompt":"「___日本語を勉強しますか。」(¿Por qué estudias japonés?)","options":["どうして","いつ","どこ","なに"],"answer":"どうして"},
  {"type":"exercise-mc","prompt":"「電話番号は___ですか。」(¿Cuál es tu número de teléfono?) — ¿qué interrogativo?","options":["なん","なに","いくら","どう"],"answer":"なん"},
  {"type":"exercise-mc","prompt":"¿Cuál es la diferencia entre どうして y なぜ?","options":["なぜ es más formal/escrito","Son idénticos siempre","どうして es más formal","Solo どうして puede ser pregunta"],"answer":"なぜ es más formal/escrito"},
  {"type":"exercise-tf","statement":"なに y なん siempre son intercambiables.","answer":False},
  {"type":"exercise-tf","statement":"いくら pregunta por cantidades de objetos.","answer":False},
  {"type":"exercise-tf","statement":"いつ pregunta por tiempo o fecha.","answer":True},
  {"type":"exercise-tf","statement":"どうして puede usarse para preguntar por qué.","answer":True},
  {"type":"exercise-tf","statement":"「だれ」puede usarse para objetos inanimados.","answer":False},
  {"type":"exercise-tf","statement":"「なん時」(¿qué hora?) usa なん porque sigue un contador.","answer":True},
  {"type":"exercise-tf","statement":"どう pregunta por el modo o estado de algo.","answer":True},
  {"type":"exercise-tf","statement":"どこ solo se usa para lugares físicos, nunca para lugares abstractos.","answer":False},
  {"type":"exercise-gap","prompt":"これは___ですか。(¿Qué es esto?)","options":["なに","だれ","どこ","いつ"],"answer":"なに","hint":"pregunta por objeto"},
  {"type":"exercise-gap","prompt":"___が好きですか。(¿Qué te gusta?) [antes de が]","options":["なに","なん","だれ","どう"],"answer":"なに","hint":"なに antes de が"},
  {"type":"exercise-gap","prompt":"お誕生日は___ですか。(¿Cuándo es tu cumpleaños?)","options":["いつ","どこ","だれ","なに"],"answer":"いつ","hint":"tiempo/fecha"},
  {"type":"exercise-gap","prompt":"___枚ありますか。(¿Cuántas láminas / hojas hay?) [contador]","options":["なん","なに","いくつ","いくら"],"answer":"なん","hint":"なん antes de contador"},
  {"type":"exercise-gap","prompt":"___から来ましたか。(¿De dónde eres?)","options":["どこ","いつ","だれ","なに"],"answer":"どこ","hint":"lugar de origen"},
  {"type":"exercise-gap","prompt":"このりんごは___ですか。(¿Cuánto cuestan estas manzanas?)","options":["いくら","いくつ","なに","どう"],"answer":"いくら","hint":"precio"},
],

"l15-contadores": [
  {"type":"exercise-mc","prompt":"¿Qué contador se usa para libros (冊)?","options":["さつ","まい","ほん","つ"],"answer":"さつ"},
  {"type":"exercise-mc","prompt":"¿Qué contador se usa para objetos largos y delgados (lápices, botellas)?","options":["ほん","まい","さつ","だい"],"answer":"ほん"},
  {"type":"exercise-mc","prompt":"¿Qué contador se usa para objetos planos (papel, ropa, platos)?","options":["まい","ほん","さつ","つ"],"answer":"まい"},
  {"type":"exercise-mc","prompt":"¿Qué contador se usa para máquinas y vehículos?","options":["だい","ひき","まい","さつ"],"answer":"だい"},
  {"type":"exercise-mc","prompt":"¿Qué contador se usa para animales pequeños?","options":["ひき","とう","まい","だい"],"answer":"ひき"},
  {"type":"exercise-mc","prompt":"¿Cómo se dice '1 persona'?","options":["ひとり","いちにん","いちめい","ひとにん"],"answer":"ひとり"},
  {"type":"exercise-mc","prompt":"¿Cómo se dice '2 personas'?","options":["ふたり","ににん","にめい","にとり"],"answer":"ふたり"},
  {"type":"exercise-mc","prompt":"¿Cómo se dice '3 personas'?","options":["さんにん","みにん","さんり","みたり"],"answer":"さんにん"},
  {"type":"exercise-mc","prompt":"¿Cómo se dice '1 libro' (con contador)?","options":["いっさつ","ひとさつ","いちさつ","ひとつ"],"answer":"いっさつ"},
  {"type":"exercise-mc","prompt":"¿Cómo se dice '3 lápices' (objetos largos)?","options":["さんぼん","さんほん","みほん","みぼん"],"answer":"さんぼん"},
  {"type":"exercise-mc","prompt":"¿Cómo se dice '2 hojas de papel' (objetos planos)?","options":["にまい","ふたまい","にひら","ふたひら"],"answer":"にまい"},
  {"type":"exercise-mc","prompt":"¿Cómo se dice '4 personas'?","options":["よにん","しにん","よったり","したり"],"answer":"よにん"},
  {"type":"exercise-mc","prompt":"¿Cómo se dice 'una cosa' con el contador genérico ~つ?","options":["ひとつ","いちつ","ひとひ","いちこ"],"answer":"ひとつ"},
  {"type":"exercise-mc","prompt":"¿Cómo se dice 'dos cosas' con el contador genérico ~つ?","options":["ふたつ","にこ","にひ","ふたさつ"],"answer":"ふたつ"},
  {"type":"exercise-mc","prompt":"¿Cómo se dice 'tres cosas' con el contador genérico ~つ?","options":["みっつ","さんこ","みこ","さんつ"],"answer":"みっつ"},
  {"type":"exercise-mc","prompt":"¿Cómo se dice 'cuatro cosas' con el contador genérico ~つ?","options":["よっつ","しつ","よんつ","しひ"],"answer":"よっつ"},
  {"type":"exercise-mc","prompt":"¿Cómo se dice 'cinco cosas' con el contador genérico ~つ?","options":["いつつ","ごこ","ごつ","ごひ"],"answer":"いつつ"},
  {"type":"exercise-mc","prompt":"¿Qué contador usa la lectura especial ひとり / ふたり?","options":["人（にん）","匹（ひき）","枚（まい）","冊（さつ）"],"answer":"人（にん）"},
  {"type":"exercise-mc","prompt":"¿Cuántos gatos? ねこが___います。(3 gatos)","options":["さんびき","さんひき","みっきき","みひき"],"answer":"さんびき"},
  {"type":"exercise-mc","prompt":"¿Cuántas botellas? ボトルが___あります。(5 botellas)","options":["ごほん","ごぼん","いつほん","ごさつ"],"answer":"ごほん"},
  {"type":"exercise-mc","prompt":"¿Cuántas hojas? かみが___あります。(6 hojas)","options":["ろくまい","ろくほん","むまい","むつ"],"answer":"ろくまい"},
  {"type":"exercise-mc","prompt":"¿Cuántas computadoras? パソコンが___あります。(2 computadoras)","options":["にだい","ふただい","にき","ふたき"],"answer":"にだい"},
  {"type":"exercise-tf","statement":"ひとり y ふたり son las lecturas especiales para 1 y 2 personas.","answer":True},
  {"type":"exercise-tf","statement":"~つ puede usarse para contar personas.","answer":False},
  {"type":"exercise-tf","statement":"「いっぽん」es la lectura de 1 con el contador ほん (objetos largos).","answer":True},
  {"type":"exercise-tf","statement":"さんびき se usa para contar 3 animales pequeños (con sonorización).","answer":True},
  {"type":"exercise-tf","statement":"まい se usa para contar libros.","answer":False},
  {"type":"exercise-tf","statement":"El contador ~つ funciona solo hasta 9.","answer":True},
  {"type":"exercise-tf","statement":"だい se usa para contar vehículos y máquinas.","answer":True},
  {"type":"exercise-tf","statement":"「にほん」puede pronunciarse にほん (Japón) o にほん (2 objetos largos) según el contexto.","answer":True},
  {"type":"exercise-gap","prompt":"本を三___ください。(Dame tres libros.)","options":["さつ","まい","ほん","つ"],"answer":"さつ","hint":"contador de libros"},
  {"type":"exercise-gap","prompt":"学生が五___います。(Hay cinco estudiantes.)","options":["にん","まい","さつ","ほん"],"answer":"にん","hint":"contador de personas"},
  {"type":"exercise-gap","prompt":"ねこが二___います。(Hay dos gatos.)","options":["ひき","まい","さつ","だい"],"answer":"ひき","hint":"animales pequeños"},
  {"type":"exercise-gap","prompt":"シャツを一___買いました。(Compré una camisa.)","options":["まい","さつ","ほん","つ"],"answer":"まい","hint":"objeto plano"},
  {"type":"exercise-gap","prompt":"えんぴつが六___あります。(Hay seis lápices.)","options":["ぽん","まい","さつ","つ"],"answer":"ぽん","hint":"6 + ほん → ぽん"},
  {"type":"exercise-gap","prompt":"りんごを三___ください。(Dame tres manzanas — genérico.)","options":["つ","まい","ほん","さつ"],"answer":"つ","hint":"みっつ (genérico)"},
],

"l16-kanji": [
  {"type":"exercise-mc","prompt":"¿Cuál es la lectura kun de 日?","options":["ひ","にち","じつ","び"],"answer":"ひ"},
  {"type":"exercise-mc","prompt":"¿Cuál es la lectura on de 月?","options":["げつ / がつ","つき","にち","び"],"answer":"げつ / がつ"},
  {"type":"exercise-mc","prompt":"¿Qué kanji significa 'fuego'?","options":["火","水","木","土"],"answer":"火"},
  {"type":"exercise-mc","prompt":"¿Qué kanji significa 'árbol / madera'?","options":["木","土","水","金"],"answer":"木"},
  {"type":"exercise-mc","prompt":"¿Qué kanji significa 'tierra / sábado'?","options":["土","金","木","水"],"answer":"土"},
  {"type":"exercise-mc","prompt":"¿Qué kanji significa 'dinero / metal / viernes'?","options":["金","土","木","火"],"answer":"金"},
  {"type":"exercise-mc","prompt":"¿Qué kanji significa 'persona'?","options":["人","口","手","目"],"answer":"人"},
  {"type":"exercise-mc","prompt":"¿Qué kanji significa 'boca'?","options":["口","手","目","耳"],"answer":"口"},
  {"type":"exercise-mc","prompt":"¿Qué kanji significa 'mano'?","options":["手","目","耳","口"],"answer":"手"},
  {"type":"exercise-mc","prompt":"¿Qué kanji significa 'ojo'?","options":["目","耳","口","手"],"answer":"目"},
  {"type":"exercise-mc","prompt":"¿Qué kanji significa 'oreja'?","options":["耳","目","口","手"],"answer":"耳"},
  {"type":"exercise-mc","prompt":"¿Cuál es la lectura kun de 山?","options":["やま","さん","ざん","やん"],"answer":"やま"},
  {"type":"exercise-mc","prompt":"¿Cuál es la lectura kun de 川?","options":["かわ","せん","さん","がわ"],"answer":"かわ"},
  {"type":"exercise-mc","prompt":"¿Qué kanji significa 'grande'?","options":["大","小","中","上"],"answer":"大"},
  {"type":"exercise-mc","prompt":"¿Qué kanji significa 'pequeño'?","options":["小","大","下","中"],"answer":"小"},
  {"type":"exercise-mc","prompt":"¿Qué kanji significa 'dentro / mediano'?","options":["中","大","小","上"],"answer":"中"},
  {"type":"exercise-mc","prompt":"¿Qué kanji significa 'arriba'?","options":["上","下","中","大"],"answer":"上"},
  {"type":"exercise-mc","prompt":"¿Qué kanji significa 'abajo'?","options":["下","上","中","小"],"answer":"下"},
  {"type":"exercise-mc","prompt":"¿Qué kanji significa 'libro / raíz / base'?","options":["本","大","上","中"],"answer":"本"},
  {"type":"exercise-mc","prompt":"¿Cuál es el kanji de 'lunes' (día de la luna)?","options":["月曜日","日曜日","火曜日","水曜日"],"answer":"月曜日"},
  {"type":"exercise-mc","prompt":"¿Cuál es el kanji de 'martes' (día del fuego)?","options":["火曜日","水曜日","木曜日","月曜日"],"answer":"火曜日"},
  {"type":"exercise-mc","prompt":"¿Cuál es el kanji de 'miércoles' (día del agua)?","options":["水曜日","火曜日","木曜日","金曜日"],"answer":"水曜日"},
  {"type":"exercise-mc","prompt":"¿Cuál es el kanji de 'jueves' (día del árbol)?","options":["木曜日","水曜日","金曜日","土曜日"],"answer":"木曜日"},
  {"type":"exercise-mc","prompt":"¿Cuál es el kanji de 'viernes' (día del oro/metal)?","options":["金曜日","木曜日","土曜日","日曜日"],"answer":"金曜日"},
  {"type":"exercise-tf","statement":"本 significa únicamente 'libro' en japonés.","answer":False},
  {"type":"exercise-tf","statement":"日 puede leerse tanto 'ひ' (kun) como 'にち' (on).","answer":True},
  {"type":"exercise-tf","statement":"Los días de la semana en japonés se basan en los cinco elementos + sol y luna.","answer":True},
  {"type":"exercise-tf","statement":"上 y 下 son kanji opuestos (arriba y abajo).","answer":True},
  {"type":"exercise-tf","statement":"人 (persona) se lee にん solo con el contador de personas.","answer":False},
  {"type":"exercise-tf","statement":"El kanji 中 puede leerse なか (kun) y ちゅう (on).","answer":True},
  {"type":"exercise-tf","statement":"大 se lee おお en kun y だい en on.","answer":True},
  {"type":"exercise-tf","statement":"水曜日 es el miércoles.","answer":True},
  {"type":"exercise-gap","prompt":"___ようびはmonday. (lunes)","options":["月","日","火","水"],"answer":"月","hint":"月 = luna = lunes"},
  {"type":"exercise-gap","prompt":"___曜日はtuesday. (martes)","options":["火","月","水","木"],"answer":"火","hint":"火 = fuego = martes"},
  {"type":"exercise-gap","prompt":"この___は大きいです。(Esta montaña es grande.)","options":["山","川","木","水"],"answer":"山","hint":"やま = montaña"},
  {"type":"exercise-gap","prompt":"___の上に本があります。(Hay un libro encima de la mesa.)","options":["つくえ","山","川","木"],"answer":"つくえ","hint":"つくえ (mesa) no es kanji N5 elemental; la respuesta es つくえ"},
  {"type":"exercise-gap","prompt":"彼は___が大きい。(Él tiene la boca grande.)","options":["口","手","目","耳"],"answer":"口","hint":"口 = boca"},
  {"type":"exercise-gap","prompt":"___本語を勉強しています。(Estudio japonés.)","options":["日","月","火","水"],"answer":"日","hint":"日本語 = japonés"},
],

}

def load_file(path):
    with open(path, encoding='utf-8') as f:
        return json.load(f)

def save_file(path, data):
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

for lesson_id, new_exercises in EXERCISES.items():
    path = os.path.join(BASE, f'{lesson_id}.json')
    if not os.path.exists(path):
        print(f'SKIP (no existe): {path}')
        continue
    data = load_file(path)
    # data is a list of blocks
    data.extend(new_exercises)
    save_file(path, data)
    total_ex = sum(1 for b in data if str(b.get('type','')).startswith('exercise-'))
    print(f'{lesson_id}: {total_ex} ejercicios tras añadir {len(new_exercises)}')

print('Done.')
